server:
  port: 9999
  contextPath : /mvvmweb
spring:
  application:
    name: mvvmweb
eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
    
    
logging:
#  file: logs/web-client.log
  level:
    ROOT: INFO