server:
  port: 8888
spring:
  application:
    name: redisService
  redis:
    database : 0
    host : 192.168.31.196
    password : ygredis
    port : 6379
    pool :
      maxIdle : 8
      minIdle : 0
      maxActive : 8
      maxWait : -1
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
    healthcheck:
      enabled : true
    
    
logging:
#  file: logs/eureka-client.log
  level:
    ROOT: INFO
