server:
  port: 9090
  contextPath : /mobile
spring:
  application:
    name: mobile
eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
    
    
logging:
#  file: logs/mobile-client.log
  level:
    ROOT: INFO